[tools]
rojo = "rojo-rbx/rojo@7.7.0"
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.4.2"
stylua = "JohnnyMorganz/StyLua@2.1.0"
selene = "Kampfkarren/selene@0.28.0"
lune = "lune-org/lune@0.10.5"
